# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "AxgHDKHvhQCRb+EoWejxkuAeyjZSWNyFvROjXS1l5eldkuUguvDfusRM53JX0+HuFHdQ7l1i9okl2BlN/pJeEm/id/fagrGm4s6EOsMbN3q4ToqzvAsGi2T4qeH/oIuKX0gsLaqNKmnM9BCX1Y4u+WvauKcbRMKlBCha1RpFMbX1H4OFvjbuOwbDC/7lhU46ipZeUwj0Y+HGvzBbFlHJ2fkci2rCSnmEyRoynuU8eVny8bsPXhXyv7SAYMUDfWMm5NrIN9XRUT684erLr07euvPfoDzffaBLJjMpHl/aCwKZsszjJwvNV0TPLnF6JLEGtmVLv8w91U0//6wxaTvR2CzexEkaOQ/KZ/rhzJFrzytFXunaIrmedZ0AMTKgWmfMOULjZEu0mpIkbVnAFgodGHyEO870WIVLboaFtjyykh+Myo6kMwvM1Zrx9ugPnNSflCmxYS45ba47eTYj6kDfYuF+dsft6hI0VEL2eHk2T2mTrmEqFND2zNz4Ov0HfWZTAg7FukkNTgJWRnTyCCpUg8tRCmeZCqR0NYiZHoS1+nm3aCRt3sXWUCSLZ4Mc5ykr80n4x0hjjP7mGcMA5JDFY8tEoCZj53C4T8U1UXwwXuwLuzOvwN5O0ENIHcIsZ6xFsbcJ5dfDTPk86bYzxRIxWU3r9fTIepm9p80xiprBg/s="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
