travis:
  secure:
    BINSTAR_TOKEN: AxgHDKHvhQCRb+EoWejxkuAeyjZSWNyFvROjXS1l5eldkuUguvDfusRM53JX0+HuFHdQ7l1i9okl2BlN/pJeEm/id/fagrGm4s6EOsMbN3q4ToqzvAsGi2T4qeH/oIuKX0gsLaqNKmnM9BCX1Y4u+WvauKcbRMKlBCha1RpFMbX1H4OFvjbuOwbDC/7lhU46ipZeUwj0Y+HGvzBbFlHJ2fkci2rCSnmEyRoynuU8eVny8bsPXhXyv7SAYMUDfWMm5NrIN9XRUT684erLr07euvPfoDzffaBLJjMpHl/aCwKZsszjJwvNV0TPLnF6JLEGtmVLv8w91U0//6wxaTvR2CzexEkaOQ/KZ/rhzJFrzytFXunaIrmedZ0AMTKgWmfMOULjZEu0mpIkbVnAFgodGHyEO870WIVLboaFtjyykh+Myo6kMwvM1Zrx9ugPnNSflCmxYS45ba47eTYj6kDfYuF+dsft6hI0VEL2eHk2T2mTrmEqFND2zNz4Ov0HfWZTAg7FukkNTgJWRnTyCCpUg8tRCmeZCqR0NYiZHoS1+nm3aCRt3sXWUCSLZ4Mc5ykr80n4x0hjjP7mGcMA5JDFY8tEoCZj53C4T8U1UXwwXuwLuzOvwN5O0ENIHcIsZ6xFsbcJ5dfDTPk86bYzxRIxWU3r9fTIepm9p80xiprBg/s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
